[package]

name    = "mondriant"
version = "0.0.0"
authors = [ "Michael White <mwhite85@gmail.com>" ]

[dependencies]
rand    = "0.3"

[dependencies.image]
git     = "https://github.com/PistonDevelopers/image.git"

